services:
  b0095_b.backend:
    image: njavilas/helloword:go
    expose:
      - 8080

    networks:
      boxer:
        aliases:
          - b0095_b.backend.boxer.net

  b0095_b.frontend:
    image: njavilas/helloword:nginx
    expose:
      - 80

    networks:
      boxer:
        aliases:
          - b0095_b.frontend.boxer.net

  b0095_b.proxy:
    image: njavilas/proxy:nginx
    ports:
      - "7000:80"

    environment:
      - FRONTEND_SERVER_NAME=b0095_b.frontend.boxer.net
      - FRONTEND_SERVER_PORT=80

      - BACKEND_SERVER_NAME=b0095_b.backend.boxer.net
      - BACKEND_SERVER_PORT=8080

    networks:
      boxer:
        aliases:
          - b0095_b.boxer.net

networks:
  boxer:
    external: true